In [0]:
from google.colab import files

In [0]:
foo = files.upload()
foo = None

Saving kaggle.json to kaggle.json


In [0]:
!chmod 600 kaggle.json

In [0]:
!mv kaggle.json /root/.kaggle

In [0]:
!kaggle competitions download -c 20-newsgroups-ciphertext-challenge

  0% 0.00/556k [00:00<?, ?B/s]
100% 556k/556k [00:00<00:00, 38.2MB/s]
 62% 10.0M/16.2M [00:00<00:00, 43.1MB/s]
100% 16.2M/16.2M [00:00<00:00, 54.0MB/s]
 86% 6.00M/6.98M [00:00<00:00, 62.8MB/s]
100% 6.98M/6.98M [00:00<00:00, 64.3MB/s]


In [0]:
!ls

sample_data		   test.csv	 train.csv
sample_submission.csv.zip  test.csv.zip  train.csv.zip


In [0]:
!unzip test.csv.zip
!unzip train.csv.zip

Archive:  test.csv.zip
  inflating: test.csv                
Archive:  train.csv.zip
  inflating: train.csv               


In [0]:
!rm /root/.kaggle/kaggle.json

In [0]:
import keras.layers as KL
from keras.applications.inception_resnet_v2 import InceptionResNetV2

In [0]:
input_tensor = KL.Input((300,128,3), name='input_tensor')
#triple_tensor = KL.Concatenate(name='triple_tensor')([input_tensor, input_tensor, input_tensor])

In [0]:
inception_model = InceptionResNetV2(include_top=False,
                      weights='imagenet',
                      input_tensor=None,
                      input_shape=(300, 128, 3),
                      pooling='avg',
                      classes=20)(input_tensor)
#classes arg probably not needed
#pooling based on default if top was included, don't know if avg is good

219062272/219055592 [==============================] - 16s 0us/step


In [0]:
from keras.models import Model

In [0]:
dropout = KL.Dropout(rate=0.2)(inception_model)
prediction = KL.Dense(20, activation='softmax', name='predictions')(dropout)
model = Model(inputs=[input_tensor], outputs=[prediction])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_tensor (InputLayer)    (None, 300, 128, 3)       0         
_________________________________________________________________
inception_resnet_v2 (Model)  (None, 1536)              54336736  
_________________________________________________________________
dropout_1 (Dropout)          (None, 1536)              0         
_________________________________________________________________
predictions (Dense)          (None, 20)                30740     
Total params: 54,367,476
Trainable params: 54,306,932
Non-trainable params: 60,544
_________________________________________________________________


inception_model = InceptionResNetV2(include_top=True,
                      weights=None,#'imagenet',
                      #input_tensor=None,
                      #input_shape=(300, 128, 3),
                      pooling=None)
                      #classes=20)
inception_model.get_layer("predictions").output
inception_model.layers[0].output

In [0]:
import pandas as pd
import numpy as np

In [0]:
train = pd.read_csv('train.csv')

In [0]:
train_diff_in = pd.get_dummies(train['difficulty'], dtype='float32')
np_diff_in = train_diff_in.values
np_diff_in.dtype

In [0]:
train_diff_in = None

In [0]:
row_num = train['ciphertext'].size
np_inputs = np.zeros((row_num, 300), dtype=np.byte)#np.float32)
np_inputs.dtype

dtype('int8')

for i, e in train['ciphertext'][:1000].iteritems():
  
  h = len(e)
  if h != 300:
    print("%d" % h)
    if (h == 4):
      print("%s %d" % (e, i))

In [0]:
for i, e in train['ciphertext'][:1000].iteritems():

  encoded = e.encode("ascii", errors='strict')
  lmao = np.frombuffer(encoded, dtype=np.byte)
  np_inputs[i, :lmao.shape[0]] = lmao

In [0]:
train.iloc[357]

Id            ID_ea014116e
difficulty               1
ciphertext            


s
target                   5
Name: 357, dtype: object

In [0]:
np_inputs[357]

array([ 12,  12,  12, 115,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [0]:
a = np.array([1, 0, 3])
b = np.zeros((3, 4))
#b[np.arange(3), a] = 1
#b

In [0]:
b[[0,1,2], a] = 1

In [0]:
b

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.arange(3)

array([0, 1, 2])

In [0]:
a = np_inputs[357]
b = np.zeros((300, 128))
b[np.arange(300),a] = 1
b

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [0]:
b[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

the_other_thing = np.zeros((row_num, 300, 128))

In [0]:
from keras.utils import plot_model

Using TensorFlow backend.


In [0]:
plot_model(model, to_file='model.png')

In [0]:
from google.colab import files

In [0]:
files.download('model.png')

In [0]:
thing = model.get_layer('inception_resnet_v2')

In [0]:
type(thing)

keras.engine.training.Model