# Preprocessing

run for each difficulty

## Environment

In [0]:
#some dtype problem that came out only in 0.23 for get_dummies
!pip3 install --upgrade pandas

In [0]:
from google.colab import files

In [0]:
foo = files.upload()
foo = None

Saving kaggle.json to kaggle.json


In [0]:
!chmod 600 kaggle.json

In [0]:
!mkdir /root/.kaggle
!mv kaggle.json /root/.kaggle/kaggle.json

In [0]:
!kaggle competitions download -c 20-newsgroups-ciphertext-challenge

  0% 0.00/556k [00:00<?, ?B/s]
100% 556k/556k [00:00<00:00, 36.5MB/s]
 31% 5.00M/16.2M [00:00<00:00, 17.5MB/s]
100% 16.2M/16.2M [00:00<00:00, 46.5MB/s]
 72% 5.00M/6.98M [00:00<00:00, 21.6MB/s]
100% 6.98M/6.98M [00:00<00:00, 27.6MB/s]


In [0]:
!unzip test.csv.zip
!unzip train.csv.zip

Archive:  test.csv.zip
  inflating: test.csv                
Archive:  train.csv.zip
  inflating: train.csv               


In [0]:
!rm /root/.kaggle/kaggle.json

In [0]:
!ls

sample_data		   test.csv	 train.csv
sample_submission.csv.zip  test.csv.zip  train.csv.zip


## Cosine similarity

Now I will attempt to pick my triplets using pure cosine similarity.

http://www.cs.trincoll.edu/~crypto/resources/LetFreq.html

4.5 characters on average per English word

https://quotabulary.com/short-meaningful-quotes

suppose shortest sentence identifiable from a source such as a quote, is 10 words.

Then 10 times 4.5 is 45. Filter from here

In [0]:
from keras.applications.inception_resnet_v2 import InceptionResNetV2
from keras.models import Model
import keras.layers as KL

Using TensorFlow backend.


In [0]:
input_x = KL.Input((300,))
input_y = KL.Input((300,))

In [0]:
output = KL.Dot(axes=-1, normalize=True)([input_x, input_y])

In [0]:
cosine_sim = Model(inputs=[input_x, input_y], outputs=output)

In [0]:
import numpy as np
import pandas as pd

In [0]:
train = pd.read_csv('train.csv')

In [0]:
print(len(train.index))

39052


In [0]:
filtered = train[train['ciphertext'].str.len() >= 45]

In [0]:
print(len(filtered.index))

38219


run any of these four

In [0]:
THE_DIFF = 1

In [0]:
THE_DIFF = 2

In [0]:
THE_DIFF = 3

In [0]:
THE_DIFF = 4

end

In [0]:
diff = filtered.loc[filtered['difficulty'] == THE_DIFF]

In [0]:
group_it = [diff[diff['target']==i] for i in range(0, 20)]

**sanity**

In [0]:
group_it[0].head()

Id  difficulty  \
49   ID_a34e9298c           1   
89   ID_6bbd51ab7           1   
106  ID_14eec1204           1   
170  ID_89c1209e4           1   
182  ID_8c304c705           1   

                                            ciphertext  target  
49   #1#8ada^vs1[a1t01#O8-1^]1ad1_^##_t&1...       0  
89   o1+avt11e^vts1[1'0a8^v^'0#v1OA1t0^8^daOv...       0  
106  8^W1vc_01za81OAs1[vc]]#ad1t^1^__c#1Ov1W1v...       0  
170  [t01Ad#1^]1Od81_^_tad1t0-T1:1_O1A...       0  
182  1A#azad1]^#_10aAs1[[`[t01-OvvO_#v1a1E...       0

In [0]:
group_it[0].index[0]

49

In [0]:
group_it[0].loc[49]

Id                                                 ID_a34e9298c
difficulty                                                    1
ciphertext    #1#8ada^vs1[a1t01#O8-1^]1ad1_^##_t&1...
target                                                        0
Name: 49, dtype: object

**end sane**

In [0]:
length_it = [[i, len(e.index)] for i, e in enumerate(group_it)]

In [0]:
length_it

[[0, 458],
 [1, 358],
 [2, 928],
 [3, 373],
 [4, 316],
 [5, 638],
 [6, 261],
 [7, 422],
 [8, 376],
 [9, 399],
 [10, 419],
 [11, 616],
 [12, 421],
 [13, 582],
 [14, 454],
 [15, 567],
 [16, 582],
 [17, 685],
 [18, 533],
 [19, 370]]

In [0]:
l = len(length_it)

In [0]:
import random

In [0]:
r = random.seed(a=42)

In [0]:
np.random.seed(42)

In [0]:
def get_it(size):
  
  x = np.arange(size)
  np.random.shuffle(x)
  return x

In [0]:
random_it = [get_it(how_long) for _,how_long in length_it]

In [0]:
for e in random_it:
  print(e[:5])

[304  39 341 218 155]
[138 206  63 134  66]
[190 659 455 387 431]
[329  80  50 306 198]
[ 95 259 305 152 248]
[332 252 214 520 459]
[122 142  59  70  21]
[225 152 145  42 130]
[305 316  13 163 122]
[341 253 356 235 398]
[392 174 190 225 280]
[355 458  79 520  32]
[ 58  39   2 239 345]
[451  85 416 242 414]
[ 38 193 311 160 141]
[469 156 547 345 303]
[ 18 241 531 557  59]
[353 627 377 158 222]
[ 12 484 251 257 474]
[325  26  86 209 346]


In [0]:
for e in random_it:
  print(e[-5:])

[106 270 348 435 102]
[284 184  85 143 153]
[ 50 633  60 671  92]
[ 71 343 116 213 318]
[ 35 297 240 311  70]
[396 636  20 553 421]
[226 202 141  88 160]
[304 394 125 418 401]
[  6  54  32 152 223]
[161 269 288 313  77]
[335  85  92 320 311]
[210  37 427 446 200]
[287 180  94 338 414]
[273 171 486 270 116]
[187 227 438 104 105]
[440 446 266 306 391]
[  3 375 268 518  92]
[114 328 609 263 541]
[421  46  98 370 298]
[ 32 175 193 343 252]


In [0]:
into_x = np.empty((1, 300,))
into_y = np.empty((1, 300,))

In [0]:
def encode_it(thingy, into):
  into[0, :] = 0
  encoded = thingy.encode("ascii", errors='strict')
  np_enc = np.frombuffer(encoded, dtype=np.byte)
  how_big = np_enc.shape[0]
  into[0, :how_big] = np_enc

In [0]:
coords = []
similarities = []

In [0]:
#i = 0

In [0]:
while l > 1:
  
  index = random.randint(0, l-1)
  first = length_it.pop(index)
  
  index = random.randint(0, l-2)
  second = length_it[index]
  
  first[1] -= 1
  if first[1] > 0:
    
    length_it.append(first)

  second[1] -= 1
  if second[1] <= 0:

    length_it.pop(index)
    
  l = len(length_it)
  
  f_g = group_it[first[0]]
  s_g = group_it[second[0]]
  f_r = random_it[first[0]][first[1]]
  s_r = random_it[second[0]][second[1]]
  #print(f_g0)
  #print(s_g0)
  #print(first)
  #print(second)
  #print(f_r1)
  #print(s_r1)
  encode_it(f_g.iloc[f_r]['ciphertext'], into_x)
  encode_it(s_g.iloc[s_r]['ciphertext'], into_y)
  
  #coords.append((first[0], f_r, second[0], s_r))
  coords.append((f_g.index[f_r], s_g.index[s_r]))
  similarities.append(cosine_sim.predict([into_x, into_y])[0,0])
  
  #if i % 100 == 0:
    
  #  print(length_it)
    
  #i += 1

**sanity**

In [0]:
i

4631

In [0]:
for i in range(0,100):
  
  print("%s, %s" % (coords[i], similarities[i]))

In [0]:
length_it

[[2, 320]]

In [0]:
len(coords)

4631

**end**

In [0]:
np_this = np.array(similarities, dtype='float32')

In [0]:
summarize_this = pd.DataFrame(np_this)

In [0]:
summarize_this.head()

0
0  0.825083
1  0.818399
2  0.830611
3  0.835075
4  0.826404

In [0]:
summarize_this.describe()

0
count  4719.000000
mean      0.772844
std       0.112751
min       0.290666
25%       0.795486
50%       0.815047
75%       0.827337
max       0.907753

**sanity**

In [0]:
counts = np.zeros(shape=(20,))

In [0]:
for f, _, s, _ in coords:
  
  counts[f] += 1
  counts[s] += 1

In [0]:
counts.shape

(20,)

In [0]:
counts

array([414., 463., 352., 334., 303., 449., 348., 324., 369., 469., 533.,
       551., 335., 475., 566., 752., 464., 702., 665., 394.])

**end sane**

In [0]:
coords_df = pd.DataFrame(coords)

In [0]:
coords_df.head()

0      1
0  33741   9358
1   7897  22479
2  14903  26707
3   7426  31054
4   4359  37705

diff 1

In [0]:
test = summarize_this[summarize_this[0] > 0.5]
len(test)

4321

In [0]:
test = summarize_this[summarize_this[0] > 0.76]
len(test)

3507

In [0]:
selection = coords_df[summarize_this[0] > 0.76]

diff 2

In [0]:
test = summarize_this[summarize_this[0] > 0.79]
len(test)

3689

In [0]:
selection = coords_df[summarize_this[0] > 0.79]

diff 3

In [0]:
test = summarize_this[summarize_this[0] > 0.79]
len(test)

3571

In [0]:
selection = coords_df[summarize_this[0] > 0.79]

diff 4

In [0]:
test = summarize_this[summarize_this[0] > 0.79]
len(test)

3658

In [0]:
selection = coords_df[summarize_this[0] > 0.79]

end

In [0]:
selection.to_csv("coords_%d.csv" % THE_DIFF, index=False)

In [0]:
test.to_csv("cosines_%d.csv" % THE_DIFF, index=False)

In [0]:
files.download("coords_%d.csv" % THE_DIFF)

In [0]:
files.download("cosines_%d.csv" % THE_DIFF)

**sanity**

In [0]:
encode_it(train.iloc[6362]['ciphertext'], into_x)
encode_it(train.iloc[10069]['ciphertext'], into_y)

In [0]:
cosine_sim.predict([into_x, into_y])

array([[0.79114914]], dtype=float32)